name: push pipeline

on:
  push:
    branches:
      - main

jobs:
    push_pipeline:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: '20'
          - name: Install dependencies (back)
            working-directory: .
            run: npm install
          - name: Install dependencies (front)
            working-directory: ./frontend
            run: npm install   
          - name: Check style
            working-directory: .
            run: npm run lint
          - name: build
            working-directory: .
            run: npm run build:ui
          - name: e2e tests
            uses: cypress-io/github-action@v5
            with:
              command: npm run test:e2e
              start: npm run dev
              wait-on: http://localhost:3001
          - name: Notify Discord on Success
            if: success()
            uses: rjstone/discord-webhook-notify@v1.0.4
            with:
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
                username: 'GitHub Actions'
                text: 'A new version has been successfully pushed 🚀'
          - name: Notify Discord on Failure
            if: failure()
            uses: rjstone/discord-webhook-notify@v1.0.4
            with:
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
                username: 'GitHub Actions'
                text: 'The build has failed ❌ Check the logs for details.'