name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
    push_pipeline:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v5
          - uses: actions/setup-node@v5
            with:
              node-version: '20'
          - name: Install dependencies 
            run: npm install  
          - name: Check style
            run: npm run lint
          - name: build
            run: npm run build

          